### ISSUE TITLE
benchmark stops prematurely  on  Monitoring EC2 instance provisioning...

### ISSUE THREAD

**Issue by TomasBahnik** [moebaca/k8s-autoscaler-benchmarker#1]
I have tried your benchmarker  with  example nodepool  adjusted to `apiVersion: karpenter.sh/v1` leading to changes

```
      nodeClassRef:
        # unknown field "spec.template.spec.nodeClassRef.apiVersion
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: k8s-autoscaler-benchmarker
...

  #  spec.amiSelectorTerms: Required value,
  amiSelectorTerms:
    - alias: al2023@v20250410
  # if set, amiFamily must be 'AL2023' or 'Custom' when using an AL2023 alias
  # amiFamily: Bottlerocket
```

The test stays on 

```
./k8s-autoscaler-benchmarker --nodepool k8s-autoscaler-benchmarker --kubeconfig ~/.kube/aws/eks-poc-config.yaml
Using node label selector: karpenter.sh/nodepool=k8s-autoscaler-benchmarker
Testing with Karpenter autoscaler...
Creating new deployment with name "inflate"
Creating deployment...
Created deployment "inflate" in namespace "default".
Monitoring EC2 instance provisioning...
Provisioning timeout exceeded. There may be an issue (check pod for errors). Do you want to continue waiting to troubleshoot issue? [yes/no]: 
```

On the backend 

```
kubectl describe pod inflate-7d77b855fc-7m8j2

Normal   Scheduled         9m25s  default-scheduler  Successfully assigned default/inflate-7d77b855fc-7m8j2 to ip-10-1-1-196.eu-central-1.compute.internal
  Normal   Nominated         10m    karpenter          Pod should schedule on: nodeclaim/k8s-autoscaler-benchmarker-5mgnj
  Normal   Pulling           9m23s  kubelet            Pulling image "public.ecr.aws/eks-distro/kubernetes/pause:3.7"
  Normal   Pulled            9m20s  kubelet            Successfully pulled image "public.ecr.aws/eks-distro/kubernetes/pause:3.7" in 2.938s (2.938s including waiting). Image size: 2002080 bytes.
  Normal   Created           9m20s  kubelet            Created container inflate
  Normal   Started           9m20s  kubelet            Started container inflate

kubectl get nodepools
NAME                         NODECLASS                    NODES   READY   AGE
core                         default                      1       True    10d
default                      default                      0       True    15d
k8s-autoscaler-benchmarker   k8s-autoscaler-benchmarker   1       True    22h
supplementary                default                      1       True    10d

kubectl get nodes
NAME                                                  STATUS   ROLES    AGE   VERSION
...
ip-10-1-1-196.eu-central-1.compute.internal           Ready    <none>   11m   v1.31.5-eks-5d632ec
...

kubectl get pods --all-namespaces --field-selector spec.nodeName=ip-10-1-1-196.eu-central-1.compute.internal
NAMESPACE     NAME                                        READY   STATUS    RESTARTS   AGE
default       inflate-7d77b855fc-7m8j2                    1/1     Running   0          13m
kube-system   aws-node-fqk7g                              2/2     Running   0          12m
kube-system   ebs-csi-node-gfcr7                          3/3     Running   0          12m
kube-system   eks-pod-identity-agent-g2h8g                1/1     Running   0          12m
kube-system   kube-proxy-c4scn                            1/1     Running   0          12m
prometheus    prometheus-prometheus-node-exporter-hxcjp   1/1     Running   0          12m
```

Any idea or hint why the test stops prematurely?

Thanks for any hint

Tomas
